### ISSUE TITLE
Save-Analysis has been removed from rust

### ISSUE THREAD

**Issue by Dr-Emann** [est31/warnalyzer#10]
See rust-lang/rust#101841

**Comment by Dr-Emann** [comment]
Ah, the title of the issue didn't seem to be relevant (not knowing what SCIP is), so I didn't see an issue for this.

**Comment by est31** [comment]
I've edited the title of #9 to mention save analysis. I wanted to work on this but my new job is a bit demanding so I am not sure i can dedicate time to this right now!

**Comment by Dr-Emann** [comment]
Perfect, thanks!
