### ISSUE TITLE
Save analysis is gone, migrate to SCIP

### ISSUE THREAD

**Issue by est31** [est31/warnalyzer#9]
[save-analysis is going away](https://github.com/rust-lang/rust/pull/101841). For the short to mid term future, we can pin nightlies but with increased MSRV requirements, this will cause issues.

Some more info on it in [this](https://old.reddit.com/r/rust/comments/xf29i2/cargoudeps_0133_release/iol237k/) reddit thread.

**Comment by b-zee** [comment]
Just wanted to come here to say I bumped into this when attempting to use this tool. `save-analysis` appears to have been removed last week, so I expect more people coming to this tool and running into a wall.

**Comment by est31** [comment]
Yeah you will have to use a pinned older nightly, until I find time to migrate to SCIP. It's obviously not a trivial effort.

**Comment by b-zee** [comment]
Yes, sorry if that came across as rude. This tool was perfect for my use case today. I can imagine it's not an easy task to migrate. Thanks a lot for your past work on this!

**Comment by est31** [comment]
@b-zee no need to worry, you weren't rude or anything. :heart:

**Comment by Matt3o12** [comment]
> Yeah you will have to use a pinned older nightly, until I find time to migrate to SCIP. It's obviously not a trivial effort.

Do you know which nightly release is the newest that still has save-analysis?

**Comment by est31** [comment]
@Matt3o12 I'd try the 2023 February 15 or 16 binary, judging by [this](https://github.com/rust-lang/rust/pull/101841#event-8537301365).

**Comment by lsunsi** [comment]
I was so happy I found this crate, and then I saw it needed work to keep working. What does this migration entail? I don't think I have anything to offer, but I'd greatly benefit from having unused check across crates, so I want to at least subscribe to this.

**Comment by est31** [comment]
The algorithmic part of this crate is rather small, most of it is in the parsing of the save analysis. So it would amount to a rewrite really.

**Comment by fenollp** [comment]
Is there a somewhat detailed plan that splits the move to SCIP in smaller parts? I'd like to get involved.

Finding dead code across crates sounds very useful to us :)

**Comment by est31** [comment]
@fenollp your bump of this issue, and me wanting to fix it for a long time, has led me to actually work on it. I've pushed the new scip backend to master. Haven't tried it on anything big yet. enjoy.

**Comment by b-zee** [comment]
Thanks a lot for the refactor, @est31! :tada: Will try it soon.

**Comment by cpg314** [comment]
FYI, in the meantime I had an alternative implementation at https://github.com/cpg314/cargo-workspace-unused-pub, tested on a fairly large workspace. It would be interesting to see how they compare. I'll update the README to mention the new SCIP backend of `warnalyzer`.
